less sudo, more root

diff --git a/node_builder/make_node b/node_builder/make_node
--- a/node_builder/make_node
+++ b/node_builder/make_node
@@ -23,64 +23,7 @@ set -x
 # -------------------------------------------------------------------------
 
 legacy() {
-  # to avoid prepending command with sudo and having the build timeout waiting
-  # for a password just require that script to be run as root.
-  if [ "$EUID" -ne 0 ]
-    then echo "Please run as root"
-    exit
-  fi
 
-
-  # -------------------------------------------------------------------------
-
-  # Here are some environment variables we can set to change the behavior of the
-  # build.
-  DEBUG=${DEBUG:-}
-  # max compression is good for network transfer speeds, but does take quite a
-  # bit of time. Its nice to set to 0 while iterating and working locally.
-  PIXZ_COMPRESSION_LEVEL=${PIXZ_COMPRESSION_LEVEL:-9}
-
-
-  # make a best effort case to clean up after the build has finished.
-  function cleanup()
-  {
-    # these drives will already be unmounted if everything has gone well so just
-    # make sure it doesn't error. I could do some `if mount | grep...` mess, but
-    # this seems like an easier way to just get moving.
-
-    if mount | rg "$CHROOT_DIR"; then
-      umount "$CHROOT_DIR/proc" "$CHROOT_DIR/sys" || true
-    fi
-
-
-    # do not remove the chroot if we are running a debug build
-    [[ -z $DEBUG ]] || rm -rf "$WORK_DIR"
-  }
-
-  trap cleanup EXIT
-  # Using a work directory under `/tmp` so I can be lazy and not care about
-  # cleaning up the mount points debootstrap creates if things go awry. I reboot
-  # my machines pretty frequently so this will resolve itself.
-  WORK_DIR=$(mktemp -d --tmpdir=/tmp debootstrap.XXXX)
-  CHROOT_DIR="$WORK_DIR/chroot"
-
-  GIT_REF=$(git rev-parse --short HEAD)
-  # Should this build be marked as dirty?
-  # todo: in the future: maybe a mark work worker nodes to run dirty builds?
-  GIT_DIRTY="-dirty"
-  git diff-index --quiet HEAD -- && GIT_DIRTY=
-  # can't use ISO-8601 due to `:` in file paths
-  BUILD_TIMESTAMP=$(date --utc +%Y-%M-%d_%H%M%S)
-  OUT_DIR="$1/$BUILD_TIMESTAMP-${GIT_REF}${GIT_DIRTY}"
-
-  # I think there is a one liner using parameter expansion, but didn't want to
-  # fuss with it too much.
-  DEB_BOOTSTRAP=deb_cache
-  if [ -z "$CACHE_DIR" ]; then
-    DEB_BOOTSTRAP="/tmp/$DEB_BOOTSTRAP"
-  else
-    DEB_BOOTSTRAP="${PWD}/${CACHE_DIR}/$DEB_BOOTSTRAP"
-  fi
 
   # do this early so if there is a GPG error it fails fast
   # todo: could this be passed in a node boot time with an boot arg?
@@ -90,7 +33,6 @@ legacy() {
 
 
 
-  mkdir --parent "$OUT_DIR" "$DEB_BOOTSTRAP"
   # todo: go back to `--varient=minbase` to save more space.
   # todo: move from eoan -> focal once docker is supported.
 
@@ -283,24 +225,24 @@ build_initramfs() {
     openssh-server
   )
 
-  sudo debootstrap \
+  debootstrap \
   --cache-dir="$DEB_BOOTSTRAP" \
   --include="${packages[*]}" \
   focal \
   "$WORK_DIR" \
   http://archive.ubuntu.com/ubuntu/
 
-  sudo cp -r "$SCRIPT_DIR"/initramfs-tools/* "$WORK_DIR/etc/initramfs-tools/"
+  cp -r "$SCRIPT_DIR"/initramfs-tools/* "$WORK_DIR/etc/initramfs-tools/"
   run_script_in_chroot "${WORK_DIR}" <(update-initramfs -u)
   # Implement insecurity
   run_script_in_chroot "${WORK_DIR}" <(passwd -d root) # remove password on root account
 
   # todo: add my ssh key
-  sudo sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' "${WORK_DIR}/etc/ssh/sshd_config"
-  sudo sed -i 's/PermitEmptyPasswords no/PermitEmptyPasswords yes/' "${WORK_DIR}/etc/ssh/sshd_config"
+  sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' "${WORK_DIR}/etc/ssh/sshd_config"
+  sed -i 's/PermitEmptyPasswords no/PermitEmptyPasswords yes/' "${WORK_DIR}/etc/ssh/sshd_config"
 
-  sudo cp -p "${WORK_DIR}/boot"/vmlinuz-*    "${OUT_DIR}/vmlinuz"
-  sudo cp -p "${WORK_DIR}/boot"/initrd.img-* "${OUT_DIR}/initramfs"
+  cp -p "${WORK_DIR}/boot"/vmlinuz-*    "${OUT_DIR}/vmlinuz"
+  cp -p "${WORK_DIR}/boot"/initrd.img-* "${OUT_DIR}/initramfs"
   chown 755 "${OUT_DIR}/vmlinuz" "${OUT_DIR}/initramfs"
 }
 
@@ -360,7 +302,7 @@ run_script_in_chroot() {
     cp -r --dereference "$script_dir" "$CHROOT_DIR/$tmp_script_dir/"
   fi
 
-  sudo chroot "$CHROOT_DIR" /usr/bin/env DEBIAN_FRONTEND=noninteractive PATH=/usr/sbin:/usr/bin/:/bin:/sbin:/usr/local/bin bash "$tmp_script_dir/$module_name/$script_name" "${args[@]}"
+  chroot "$CHROOT_DIR" /usr/bin/env DEBIAN_FRONTEND=noninteractive PATH=/usr/sbin:/usr/bin/:/bin:/sbin:/usr/local/bin bash "$tmp_script_dir/$module_name/$script_name" "${args[@]}"
 
   rm -r "${CHROOT_DIR:?}/$tmp_script_dir"
 }
@@ -394,6 +336,51 @@ while (( "$#" )); do
   esac
 done
 
+
+
+
+# -------------------------------------------------------------------------
+
+# Here are some environment variables we can set to change the behavior of the
+# build.
+DEBUG=${DEBUG:-}
+# max compression is good for network transfer speeds, but does take quite a
+# bit of time. Its nice to set to 0 while iterating and working locally.
+PIXZ_COMPRESSION_LEVEL=${PIXZ_COMPRESSION_LEVEL:-9}
+
+
+# make a best effort case to clean up after the build has finished.
+function cleanup()
+{
+  # these drives will already be unmounted if everything has gone well so just
+  # make sure it doesn't error. I could do some `if mount | grep...` mess, but
+  # this seems like an easier way to just get moving.
+
+  if mount | rg "$CHROOT_DIR"; then
+    umount "$CHROOT_DIR/proc" "$CHROOT_DIR/sys" || true
+  fi
+
+
+  # do not remove the chroot if we are running a debug build
+  [[ -z $DEBUG ]] || rm -rf "$WORK_DIR"
+}
+
+trap cleanup EXIT
+# Using a work directory under `/tmp` so I can be lazy and not care about
+# cleaning up the mount points debootstrap creates if things go awry. I reboot
+# my machines pretty frequently so this will resolve itself.
+WORK_DIR=$(mktemp -d --tmpdir=/tmp debootstrap.XXXX)
+CHROOT_DIR="$WORK_DIR/chroot"
+
+GIT_REF=$(git rev-parse --short HEAD)
+# Should this build be marked as dirty?
+# todo: in the future: maybe a mark work worker nodes to run dirty builds?
+GIT_DIRTY="-dirty"
+git diff-index --quiet HEAD -- && GIT_DIRTY=
+# can't use ISO-8601 due to `:` in file paths
+BUILD_TIMESTAMP=$(date --utc +%Y-%M-%d_%H%M%S)
+OUT_DIR="$1/$BUILD_TIMESTAMP-${GIT_REF}${GIT_DIRTY}"
+
 # I think there is a one liner using parameter expansion, but didn't want to
 # fuss with it too much.
 DEB_BOOTSTRAP=deb_cache
@@ -402,8 +389,17 @@ if [ -z "$CACHE_DIR" ]; then
 else
   DEB_BOOTSTRAP="${PWD}/${CACHE_DIR}/$DEB_BOOTSTRAP"
 fi
-mkdir -p "$DEB_BOOTSTRAP"
+mkdir --parent "$OUT_DIR" "$DEB_BOOTSTRAP"
+
 SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+
+
+# to avoid prepending command with sudo and having the build timeout waiting
+# for a password just require that script to be run as root.
+if [ "$EUID" -ne 0 ]
+  then echo "Please run as root"
+  exit
+fi
 
 $BUILD_KERNEL    && build_kernel
 $BUILD_INITRAMFS && build_initramfs
