working on ramroot

diff --git a/node_builder/make_node b/node_builder/make_node
--- a/node_builder/make_node
+++ b/node_builder/make_node
@@ -78,16 +78,57 @@ build_initramfs() {
   cp -p --dereference "${WORK_DIR}/boot"/initrd.img-* "${OUT_DIR}/initramfs"
   chown kyle "${OUT_DIR}/vmlinuz" "${OUT_DIR}/initramfs"
   chmod 755 "${OUT_DIR}/vmlinuz" "${OUT_DIR}/initramfs"
+  rm -r "${WORK_DIR}"
 }
 
 build_ramroot() {
   WORK_DIR="$(mktemp --directory --tmpdir=/tmp ramroot.XXXX)"
-  date > "${WORK_DIR}/hello.txt"
+
+  packages=(
+    locales
+    openssh-server
+    pixz # need by ramroot script
+    tar # need by ramroot script
+  )
+  debootstrap \
+  --arch=amd64 \
+  --components=main,universe \
+  --cache-dir="$DEB_BOOTSTRAP" \
+  --include="${packages[*]}" \
+  focal \
+  "$WORK_DIR" \
+  http://archive.ubuntu.com/ubuntu/
+
+
+  # book keeping
+  run_script_in_chroot "${WORK_DIR}" "
+  locale-gen 'en_US.UTF-8'
+  update-locale LANG=en_US.UTF-8
+  echo \"$(git rev-parse HEAD)\" > /etc/node-build-rev
+  echo \"$BUILD_TIMESTAMP\" > /etc/node-build-date
+  "
+
+  # ssh
+  run_script_in_chroot "$WORK_DIR" "
+  # add ssh key for easier management
+  # todo: this should be injected in and not hard-coded
+  mkdir -p /root/.ssh
+  cat << SSH >> /root/.ssh/authorized_keys
+  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDZq6q45h3OVj7Gs4afJKL7mSz/bG+KMG0wIOEH+wXmzDdJ0OX6DLeN7pua5RAB+YFbs7ljbc8AFu3lAzitQ2FNToJC1hnbLKU0PyoYNQpTukXqP1ptUQf5EsbTFmltBwwcR1Bb/nBjAIAgi+Z54hNFZiaTNFmSTmErZe35bikqS314Ej60xw2/5YSsTdqLOTKcPbOxj2kulznM0K/z/EDcTzGqc0Mcnf51NtzxlmB9NR4ppYLoi7x+rVWq04MbdAmZK70p5ndRobqYSWSKq+WDUAt2+CiTm6ItDowTLuo3zjHyYV1eCnB35DdakKVldIHrQyhmhbf5hJi6Ywx6XCzlFoNpkl/++RrJT2rf0XpGdlRoLQoKFvNRfnO4LI499SIfFb9Pwq7LhF1C1kTmshN/9S44d6VCCYXLE4uS8OPv7IXxUvFQZaIKCbomd2FzXxUwf4lg2gSlczysgDaVsMAUvlfDVgTFX8Xt1LFl3DqNtUiUpa9+Jnst/jCqqOBf3e8= kyle@alpha
+  SSH
+  "
+
+  # ------------------
+  # Done with chroot
+  # ------------------
+
+  umount "$WORK_DIR/proc" "$WORK_DIR/sys"
   tar --sort=name -cf "$WORK_DIR/ramroot.tar" "${WORK_DIR}"
   pixz "-$PIXZ_COMPRESSION_LEVEL" < "$WORK_DIR/ramroot.tar" > "$WORK_DIR/ramroot.tar.xz"
   cp -p "${WORK_DIR}/ramroot.tar.xz" "${OUT_DIR}/ramroot.tar.xz"
   chown kyle "${OUT_DIR}/ramroot.tar.xz"
   chmod 755 "${OUT_DIR}/ramroot.tar.xz"
+  rm -r "${WORK_DIR}"
 }
 
 run_script_in_chroot() {
@@ -209,22 +250,18 @@ PIXZ_COMPRESSION_LEVEL=${PIXZ_COMPRESSION_LEVEL:-9}
 
 
 # make a best effort case to clean up after the build has finished.
-function cleanup()
-{
-  # these drives will already be unmounted if everything has gone well so just
-  # make sure it doesn't error. I could do some `if mount | grep...` mess, but
-  # this seems like an easier way to just get moving.
-
-  if mount | rg "$CHROOT_DIR"; then
-    umount "$CHROOT_DIR/proc" "$CHROOT_DIR/sys" || true
-  fi
-
-
-  # do not remove the chroot if we are running a debug build
-  #[[ -z $DEBUG ]] || rm -rf "$WORK_DIR"
-}
-
-trap cleanup EXIT
+#function cleanup()
+#{
+#  # these drives will already be unmounted if everything has gone well so just
+#  # make sure it doesn't error. I could do some `if mount | grep...` mess, but
+#  # this seems like an easier way to just get moving.
+#
+#  if mount | rg "$CHROOT_DIR"; then
+#    umount "$CHROOT_DIR/proc" "$CHROOT_DIR/sys" || true
+#  fi
+#}
+#
+#trap cleanup EXIT
 # Using a work directory under `/tmp` so I can be lazy and not care about
 # cleaning up the mount points debootstrap creates if things go awry. I reboot
 # my machines pretty frequently so this will resolve itself.
